services:
  web:
    build: .
    ports: 
      - "3000:3000"
    volumes:
      - .:/home/node/server
      - /home/node/server/node_modules
    environment:
      - REDIS_URL=redis://redis_db:6379
    links:
      - redis_db
    
  redis_db:
    image: redis:7.0-alpine3.17
    ports:
      - "6379:6379"
    command: "redis-server"
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local


    
