services:
  web:
    build: .
    ports: 
      - "3000:3000"
    volumes:
      - .:/home/node/server
      - /home/node/server/node_modules
    links:
      - redis
    
  redis:
    image: redis:7.0-alpine3.17
    ports: 
       - "6379:6379"
    
