services:
  web:
    build: .
    ports: 
      - "3000:3000"
    volumes:
      - .:/home/node/server
      - /home/node/server/node_modules
    environment:
      - REDIS_URL=redis://redis_db:6379
      - MONGO_URL=mongodb://mongo_db:27017
    links:
      - redis_db
    tty: true
    ***REMOVED***din_open: true
    
  redis_db:
    image: redis:7.0-alpine3.17
    ports:
      - "6379:6379"
    command: "redis-server"
    tty: true
    ***REMOVED***din_open: true
    volumes:
      - cache:/data
  
  mongo_db:
    image: 
      mongo:6
    ports: 
      - "27017:27017"
    volumes:
      - mongo_data:/data

volumes:
  cache:
    driver: local
  mongo_data:
    driver: local


    
